MERGE INTO friendship_status (id, status_name) VALUES (1, 'Acknowledged');
MERGE INTO friendship_status (id, status_name) VALUES (2, 'Not acknowledged');
MERGE INTO genre (id, genre_name) VALUES (1, 'Комедия');
MERGE INTO genre (id, genre_name) VALUES (2, 'Драма');
MERGE INTO genre (id, genre_name) VALUES (3, 'Мультфильм');
MERGE INTO genre (id, genre_name) VALUES (4, 'Триллер');
MERGE INTO genre (id, genre_name) VALUES (5, 'Документальный');
MERGE INTO genre (id, genre_name) VALUES (6, 'Боевик');
MERGE INTO mpa (id, rating_name) VALUES (1, 'G');
MERGE INTO mpa (id, rating_name) VALUES (2, 'PG');
MERGE INTO mpa (id, rating_name) VALUES (3, 'PG-13');
MERGE INTO mpa (id, rating_name) VALUES (4, 'R');
MERGE INTO mpa (id, rating_name) VALUES (5, 'NC-17');
